Fix warnings when using event table macros with Clang 19.1.6
Avoid warnings about incompatible casts:

In file included from ../../tests/allheaders.cpp:369:
In file included from ../../tests/testprec.h:5:
In file included from ../../include/wx/evtloop.h:13:
../../include/wx/event.h:141:12: error: cast from 'void (wxEvtHandler::*)(wxFocusEvent &)' to 'wxEventFunction' (aka 'void (wxEvtHandler::*)(wxEvent &)') converts to incompatible function type [-Werror,-Wcast-function-type-mismatch]
  141 |     return reinterpret_cast<wxEventFunction>(func);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This warning was already suppressed on GCC; just do the same thing for
Clang also.

See #25064.

(cherry picked from commit 6561ca020048de57ec28fec5b27f80b00d445cdd)