Fix implicit declaration configuration errors with Xcode 12
Some configure could fail with errors like the following:

conftest.c:56:33: error: implicitly declaring library function 'exit'
with type 'void (int) __attribute__((noreturn))'
[-Werror,-Wimplicit-function-declaration]

See https://trac.macports.org/ticket/61672

See #22946.

(cherry picked from commit da4b42688a6cd5444eefb91bf40183d88203ffca)